

INSERT INTO USUARIO(idUsuario,nombre,APELLIDO,CORREO,TELEFONO)
VALUES (usuario_seq.nextval,'maria','perez','maria.perez@gmail.com','9517531478');
COMMIT ;

INSERT INTO PROYECTO(idproyecto, nombre, descripcion, FECHAFIN)
VALUES (PROYECTO_SEQ.nextval,'TEST_API REST','Proyecto api rest',DATE '2026-07-06');
COMMIT ;

INSERT INTO ESTADO_TAREA(idestado, nombre)
VALUES (ESTADOTAREA_SEQ.nextval,'Pendiente');
COMMIT ;

INSERT INTO TAREA(IDTAREA, TITULO, DESCRIPCION, PRIORIDAD, IDPROYECTO, IDUSUARIOASIGNADO, IDESTADO, FECHALIMITE)
VALUES (TAREA_SEQ.nextval,'Creacion controller','Crear los controladores del API REST','ALTA',1,1,1 ,DATE '2026-07-05');
COMMIT ;

INSERT INTO TAREA(IDTAREA, TITULO, DESCRIPCION, PRIORIDAD, IDPROYECTO, IDUSUARIOASIGNADO, IDESTADO, FECHALIMITE)
VALUES (TAREA_SEQ.nextval,'Creacion controller','Crear los controladores del API REST','ALTA',1,1,1 ,DATE '2026-07-05');
COMMIT ;

INSERT INTO COMENTARIO(IDCOMENTARIO, IDTAREA, IDUSUARIO, COMENTARIO)
VALUES (COMENTARIO_SEQ.nextval,1,1,'Realizar pruebas unitarias desde postman');
COMMIT ;


SELECT * FROM USUARIO;
SELECT * FROM PROYECTO;
SELECT * FROM ESTADO_TAREA;
SELECT * FROM TAREA;
SELECT * FROM COMENTARIO;



